### ISSUE TITLE
Changing Flair puck thermostat set point while it is off returns a 422 error

### ISSUE THREAD

**Issue by fcfort** [RobertD502/home-assistant-flair#30]
If the Flair Puck is in "off" mode, changing the set point temperature returns an error message to the UI. See screenshot below for an example.

This does not happen with my ecobee thermostat for instance. Instead the temperature set point is changed but the ecobee thermostat stays in the "off" state.

A better experience would be to either not allow the change or to reject the change in set point rather than return an error.

<img width="1107" alt="Screen Shot 2022-08-10 at 13 14 01" src="https://user-images.githubusercontent.com/435867/183975618-e841c862-cef8-4e31-8387-66090ec5d950.png">

Complete error message:

```
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/flair/climate.py:393
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 1:13:46 PM (2 occurrences)
Last logged: 1:13:59 PM

[2795027400] ApiError<HTTP Response: 422>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 588, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 446, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flair/climate.py", line 393, in set_temperature
    self._hvac_unit.set_hvac_temp(temp)
  File "/usr/local/lib/python3.10/site-packages/flair/hvac_units/hvac_unit.py", line 186, in set_hvac_temp
    self.api.control_hvac(self, HVAC_UNITS, attributes, relationships)
  File "/usr/local/lib/python3.10/site-packages/flair/flair_helper.py", line 230, in control_hvac
    self.client.update(resource_type, id, attributes, relationships)
  File "/usr/local/lib/python3.10/site-packages/hass_flair_api/client.py", line 248, in update
    return self.handle_resp(
  File "/usr/local/lib/python3.10/site-packages/hass_flair_api/client.py", line 339, in handle_resp
    raise ApiError(resp)
hass_flair_api.client.ApiError: ApiError<HTTP Response: 422>
```

**Comment by RobertD502** [comment]
When you say the puck is in "off" mode, are you referring to the minisplit or AC unit that you're controlling with the puck being in off mode?

**Comment by fcfort** [comment]
Yes please, happy to be a beta tester.

**Comment by RobertD502** [comment]
@fcfort Pre-Release is live. You can access the update by setting the switch "Show beta versions" to On for the Flair integration within HACS:

![image](https://user-images.githubusercontent.com/52541649/185685475-8fe3dbd3-bd30-46f9-95ed-5a69ae472b90.png)

**Post any bugs/discussion regarding 0.1.0 to the [0.1.0 Discussion](https://github.com/RobertD502/home-assistant-flair/discussions/32).**
