### ISSUE TITLE
TypeError: type NoneType doesn't define __round__ method

### ISSUE THREAD

**Issue by ma4din** [RobertD502/home-assistant-flair#89]
Hi, 

I have the following issue with my flair integration for HASS. Can you please help? 

```
Logger: homeassistant.components.automation.hvac_vent_control
Source: helpers/script.py:526
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: November 12, 2024 at 7:00:04 PM (1016 occurrences)
Last logged: 9:50:05 AM

HVAC Vent Control: Play Room: Error executing script. Unexpected error for call_service at pos 1: type NoneType doesn't define __round__ method
HVAC Vent Control: Error executing script. Unexpected error for if at pos 1: type NoneType doesn't define __round__ method
HVAC Vent Control: Play Bath Room: Error executing script. Unexpected error for call_service at pos 1: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1032, in entity_service_call
    raise result from None
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1612, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/flair/cover.py", line 175, in async_close_cover_tilt
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 273, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 358, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 544, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flair/sensor.py", line 789, in native_value
    return round(self.vent_data.current_reading['duct-pressure'], 2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method
```

**Comment by RobertD502** [comment]
Please share your automation (the YAML) to determine if there is something in it that is causing it.

**Comment by ma4din** [comment]
```
alias: HVAC Vent Control
description: ""
triggers:
  - entity_id:
      - input_boolean.hvac_elsa_room_cool_demand
      - input_boolean.hvac_playroom_cool_demand
      - input_boolean.hvac_living_room_cool_demand
      - input_boolean.hvac_martin_office_cool_demand
      - input_boolean.hvac_playroom_bath_cool_demand
      - input_boolean.hvac_elsa_bath_room_cool_demand
      - input_boolean.hvac_playroom_heat_demand
      - input_boolean.hvac_elsa_room_heat_demand
      - input_boolean.hvac_living_room_heat_demand
      - input_boolean.hvac_martin_office_heat_demand
      - input_boolean.hvac_playroom_bath_heat_demand
      - input_boolean.hvac_elsa_bath_room_heat_demand
    trigger: state
  - minutes: /5
    trigger: time_pattern
conditions: []
actions:
  - alias: Play Bath Room
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.hvac_playroom_bath_cool_demand
            state: "on"
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_playroom_bath_heat_demand
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id: cover.play_room_bath_aef0_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id: cover.play_room_bath_aef0_vent
  - alias: Play Room
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.hvac_playroom_cool_demand
            state: "on"
          - condition: state
            entity_id: input_boolean.hvac_playroom_heat_demand
            state: "on"
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id:
            - cover.play_room_cb44_vent
            - cover.play_room_080d_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id:
            - cover.play_room_cb44_vent
            - cover.play_room_080d_vent
  - alias: Elsa Room
    if:
      - condition: or
        conditions:
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_elsa_room_cool_demand
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_elsa_room_heat_demand
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id: cover.elsa_s_room_7515_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id:
            - cover.elsa_s_room_7515_vent
  - alias: Elsa Bath Room
    if:
      - condition: or
        conditions:
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_elsa_bath_room_cool_demand
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_elsa_bath_room_heat_demand
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id: cover.elsa_s_room_33b9_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id: cover.elsa_s_room_33b9_vent
    enabled: true
  - alias: Martin Office
    if:
      - condition: or
        conditions:
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_martin_office_cool_demand
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_martin_office_heat_demand
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id: cover.martin_s_office_380d_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id: cover.martin_s_office_380d_vent
  - alias: Living Room
    if:
      - condition: or
        conditions:
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_living_room_cool_demand
          - condition: state
            state: "on"
            entity_id: input_boolean.hvac_living_room_heat_demand
    then:
      - action: cover.open_cover_tilt
        data: {}
        target:
          entity_id:
            - cover.living_room_1c09_vent
            - cover.living_room_2811_vent
            - cover.living_room_3062_vent
            - cover.living_room_e27b_vent
    else:
      - action: cover.close_cover_tilt
        data: {}
        target:
          entity_id:
            - cover.living_room_e27b_vent
            - cover.living_room_3062_vent
            - cover.living_room_2811_vent
            - cover.living_room_1c09_vent
mode: queued
```

**Comment by RobertD502** [comment]
1. Go to the Flair integration (in the Home Assistant integrations page)
2) Click on "Enable debug logging"
3) Restart Home Assistant
4) Give it a minute once Home Assistant is back up and running and then navigate back to the Flair integration and disable debug logging.

A Log file should get downloaded - share that file here.

**Comment by RobertD502** [comment]
The vents causing the issue are offline and as a result the current-reading endpoint returns empty. For vents that are offline, you should see that I log a warning in the Home Assistant logs and the cover entity for vents that are offline will be unavailable in Home Assistant.

For example: Play Room Back shows 
```
"inactive": true
```

What's happening is that your automation runs and when it calls for a vent to open or to close, if the vent is unavailable, the vent won't have been controlled and, when that service call is made, the API is polled and the current-reading endpoint is empty for offline vents.

The best way to handle this is to add a check in your automation to make sure, for the vent that is having a action executed on it, the cover entity is available - if it isn't available then you can have it do something else like sending yourself a notification.

**Comment by ma4din** [comment]
Thank you. That makes sense. Do you know how exactly I can check if an entity is available? Or is there way to let the automation continue even if a servie call failes. Kind of like a IFERROR function?

**Comment by RobertD502** [comment]
I believe you can nest in another condition where you check the state of the vent that passed the initial condition. If the state is not unavailable then call the cover service. If it is unavailable then send yourself a notification. I use node red mainly, but I'm sure someone on the home assistant forums could assist you some more.
